#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright © 1997, 98, 00, 01, 02, 03 Progiciels Bourbeau-Pinard inc.
# François Pinard <pinard@iro.umontreal.ca>, 1997.

"""\
Shuffle input lines.

Usage: shuffle [FICHIER]...
"""

__metaclass__ = type
import sys

def main(*arguments):
    if arguments:
        lines = []
        for name in arguments:
            lines += file(name).readlines()
    else:
        lines = sys.stdin.readlines()
    import random
    random.shuffle(lines)
    sys.stdout.writelines(lines)

if __name__ == '__main__':
    main(*sys.argv[1:])
