#!/usr/bin/env python3
# Copyright © 2004 Progiciels Bourbeau-Pinard inc.
# François Pinard <pinard@iro.umontreal.ca>, 2004.

"""\
Tenter de deviner le jeu de caractères utilisé dans des fichiers.

Usage: charset [OPTION]... [FICHIER]...

Options:
  -h  Fournir cette aide et ne rien faire d'autre
  -m  Ajouter /minus pour un fichier sans aucune majuscule
  -M  Ajouter /majus pour un fichier sans aucune minuscule

Les jeux reconnus sont: ASCII, ISO-8859-1, UTF-8; sinon [Inconnu].
Une surface Unix n'est pas notée, les autres surfaces reconnues sont
/windows et /macintosh.  Autrement, la surface est notée [/inconnue].

Si aucun FICHIER n'est fourni, étudier l'entrée standard.
"""

import sys

class Main:
    majus = False
    minus = False

    def main(self, *arguments):
        import getopt
        options, arguments = getopt.getopt(arguments, 'hMm')
        for option, valeur in options:
            if option == '-h':
                sys.stdout.write(__doc__)
                return
            elif option == '-M':
                self.majus = True
            elif option == '-m':
                self.minus = True
        write = sys.stdout.write
        arguments = list(map(str, arguments))
        if arguments:
            largeur = max(list(map(len, arguments))) + 2
            for argument in arguments:
                try:
                    tampon = file(argument).read()
                except IOError as exception:
                    write('%*s%s\n' % (-largeur, argument, exception))
                else:
                    write('%*s%s\n' % (-largeur, argument,
                                       self.deviner(tampon)))
        else:
            tampon = sys.stdin.read()
            sys.stdout.write('%s\n' % self.deviner(tampon))

    def deviner(self, tampon):
        return (self.deviner_charset(tampon)
                + self.deviner_capitalisation(tampon)
                + self.deviner_surface(tampon))

    def deviner_charset(self, tampon):
        for charset in 'ASCII', 'UTF-8':
            try:
                tampon.decode(charset)
            except UnicodeDecodeError:
                pass
            else:
                return charset
        import re
        if not re.search('[\x80-\x9f]', tampon):
            return 'ISO-8859-1'
        return '[Inconnu]'

    def deviner_capitalisation(self, tampon):
        texte = ''
        if self.majus and tampon == tampon.upper():
            texte += '/majus'
        if self.minus and tampon == tampon.lower():
            texte += '/minus'
        return texte

    def deviner_surface(self, tampon):
        unix = False
        macintosh = False
        windows = False
        if '\r\n' in tampon:
            windows = True
            tampon = tampon.replace('\r\n', '')
        if '\r' in tampon:
            macintosh = True
        if '\n' in tampon:
            unix = True
        if unix + macintosh + windows != 1:
            return '/[inconnu]'
        if windows:
            return '/windows'
        if macintosh:
            return '/macintosh'
        return ''

run = Main()
main = run.main

if __name__ == '__main__':
    main(*sys.argv[1:])
