#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright © 1993, 1999, 2002, 2008 Progiciels Bourbeau-Pinard inc.
# François Pinard <pinard@iro.umontreal.ca>, 1993.

"""\
Prendre copie d'un écran X.

Usage: click [IMAGE]

Un click dans une fenêtre copie l'image de la fenêtre, alors que
la sélection d'une région rectangulaire ne copie que le contenu de
cette région.

IMAGE est le nom du fichier qui recevra l'image de l'image copiée,
le type de fichier produit est déterminé par l'extension.  Si IMAGE
n'est pas fourni, alors l'image est immédiatement ré-affichée dans
une autre fenêtre.
"""

__metaclass__ = type
import os, sys, time

class Main:

    def main(self, *arguments):
        import getopt
        options, arguments = getopt.getopt(arguments, '')
        for option, valeur in options:
            pass
        if arguments:
            assert len(arguments) == 1, arguments
            image = arguments[0]
        else:
            image = None
        time.sleep(3)
        if image:
            os.system('import -silent -descend -border '
                      + ' '.join(arguments))
            if image.endswith('.gif'):
                os.system('giftopnm %s | ppmtogif > %s-tmp' % (image, image))
                os.remove(image)
                os.rename(image + '-tmp', image)
        else:
            image = '/tmp/click-tmp.png'
            os.system('import -silent -descend -border ' + image)
            os.system('display ' + image)
            os.remove(image)

run = Main()
main = run.main

if __name__ == '__main__':
    main(*sys.argv[1:])
