#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright © 2003 Progiciels Bourbeau-Pinard inc.
# François Pinard <pinard@iro.umontreal.ca>, 2003.

"""\
Display ANSI colours.
"""

__metaclass__ = type
import sys

def main(*arguments):
    assert not arguments
    write = sys.stdout.write
    write(''.join(['%9d' % background for background in range(40, 48)]) + '\n')
    for foreground in range(30, 38):
        write('%d  ' % foreground)
        for background in range(40, 48):
            write('\33[%d;%dm Normal  \33[0m' % (background, foreground))
        write('\n    ')
        for background in range(40, 48):
            write('\33[%d;%d;1m Bold    \33[0m' % (background, foreground))
        write('\n')
    write('\n')
    specials = ((0, 'default'),
                (1, 'bold'),
                (4, 'underline '),
                (5, 'blink'),
                (7, 'reverse-video'),
                (8, 'invisible'))
    skip = (len(specials) + 2) // 3
    for line in range(skip):
        index = line
        while index < len(specials):
            escape, comment = specials[index]
            write('%2d   \033[%dm%-13s\033[0m' % (escape, escape, comment))
            index += skip
        write('\n')

if __name__ == '__main__':
    main(*sys.argv[1:])
