#!/usr/bin/env python3
# Copyright © 2000, 2002, 2003 Progiciels Bourbeau-Pinard inc.
# François Pinard <pinard@iro.umontreal.ca>, 2000.

"""\
Comparer deux fichiers mot à mot, avec divers affichages utiles.
Il s'agit d'un programme frontal à `wdiff'.

Usage: ediff [OPTION]... GAUCHE DROITE

Options:
  -P  Produire une sortie Postscript, via le programme `enscript'.

Sans option, ce programme produit des séquences couleur ANSI, qui sont
utiles dans une console Linux ou encore, dans un `M-x shell' de Emacs.

Si l'un de GAUCHE ou de DROITE est un répertoire et que l'autre ne l'est
pas, un fichier de même nom est présumé dans le répertoire en question.
Le résultat de la comparaison est produit sur la sortie standard.
"""

import os, subprocess, sys
from curses.ascii import NUL, SOH, ESC
nul = chr(NUL)
soh = chr(SOH)
esc = chr(ESC)

class Main:
    def __init__(self):
        self.postscript = False

    def main(self, *arguments):
        import getopt
        options, arguments = getopt.getopt(arguments, 'P')
        for option, value in options:
            if option == '-P':
                self.postscript = True
        assert len(arguments) == 2, arguments
        if self.postscript:
            Wdiff_Postscript(*arguments)
        else:
            Wdiff_Ansi(*arguments)

main = Main().main

class Wdiff:

    def __init__(self, gauche, droite):
        if os.path.isdir(gauche) and not os.path.isdir(droite):
            gauche = os.path.join(gauche, os.path.basename(droite))
        elif os.path.isdir(droite) and not os.path.isdir(gauche):
            droite = os.path.join(droite, os.path.basename(gauche))
        arguments = ['wdiff']
        if subprocess.check_output(['wdiff', '--help']).find(' -D') >= 0:
            arguments.append('-D=<>"().,/')
        arguments.append('-w' + self.start_delete)
        arguments.append('-x' + self.end_delete)
        arguments.append('-y' + self.start_insert)
        arguments.append('-z' + self.end_insert)
        arguments.append(gauche)
        arguments.append(droite)
        self.execute(arguments)

class Wdiff_Ansi(Wdiff):
    start_delete = esc + '[1;31m'
    end_delete = esc + '[0m'
    start_insert = esc + '[1;34m'
    end_insert = esc + '[0m'

    def execute(self, arguments):
        os.execlp('wdiff', *arguments)

class Wdiff_Postscript(Wdiff):
    start_delete = soh + 'bggray{.88}'
    end_delete = soh + 'bggray{1}'
    start_insert = soh + 'font{Courier-Bold@10}'
    end_insert = soh + 'font{Courier@10}'

    def execute(self, arguments):
        lecture, ecriture = os.pipe()
        enfant = os.fork()
        if enfant == 0:
            os.close(ecriture)
            subprocess.Popen(
                    ['enscript', '-G', '-e', '-p-'],
                    stdin=subprocess.PIPE).input.write(
                            os.fdopen(lecture).read().replace(soh, nul))
        else:
            os.close(lecture)
            os.dup2(ecriture, sys.stdout.fileno())
            os.execlp('wdiff', *arguments)

if __name__ == '__main__':
    main(*sys.argv[1:])
