#!/usr/bin/env python3
# Copyright © 1996, 97, 98, 99, 00, 03 Progiciels Bourbeau-Pinard inc.
# François Pinard <pinard@iro.umontreal.ca>, juin 1996.

"""\
Convert dates from some American formats to ISO format.

Usage: iso-dates [OPTION] [FICHIER]...

  -l  Traiter la sortie de `ls' ou `pax'.
"""

import sys
from Etc import isodate


def main(*arguments):
    transform = isodate.normalize
    write = sys.stdout.write
    import getopt
    options, arguments = getopt.getopt(arguments, 'l')
    for option, value in options:
        if option == '-l':
            transform = isodate.unposix
    if arguments:
        for name in arguments:
            for line in open(name):
                write(transform(line))
    else:
        for line in sys.stdin:
            write(transform(line))

if __name__ == '__main__':
    main(*sys.argv[1:])
