#!/usr/bin/perl -w
# Normalize my own ChangeLogs.
# Copyright © 1996, 1997, 1998 Progiciels Bourbeau-Pinard inc.
# François Pinard <pinard@iro.umontreal.ca>, 1996.

$month_rgxp = 'Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec';

%month_subst = ('Jan', '01', 'Feb', '02', 'Mar', '03', 'Apr', '04',
                'May', '05', 'Jun', '06', 'Jul', '07', 'Aug', '08',
                'Sep', '09', 'Oct', '10', 'Nov', '11', 'Dec', '12');

while (<>) {
    if (/^[A-Z][a-z][a-z] ($month_rgxp) ([ 0-3][0-9]) [0-2][0-9]:[0-5][0-9]:[0-5][0-9]( [A-Z][A-Z][A-Z])? (19[8-9][0-9])/o) {
        $_ = ($4 . '-' . $month_subst{$1} . '-'
              . ($2 < 10 ? "0" . ($2 + 0) : $2) . $');
        s/\(/</;
        s/\)/>/;
        s/<(.*) at (.*)>/<$1\@$2>/;

        s/=\?ISO-8859-1\?Q\?Fran=E7ois_Pinard\?=/François Pinard/;
        s/Francois Pinard/François Pinard/;
        s/<pinard\@.*>/<pinard\@iro.umontreal.ca>/;
    }
    while (/([01]?[0-9])\/([0-3]?[0-9])\/([89][0-9])/) {
        $_ = ($` . "19$3-" . (length $1 == 1 ? "0$1" : $1)
              . '-' . (length $2 == 1 ? "0$2" : $2) . $');
    }
    while (/([ 0-3][0-9]) ($month_rgxp) ([89][0-9])/o) {
        $_ = ($` . "19$3-" . $month_subst{$2} . '-'
              . ($1 < 10 ? "0" . ($1 + 0) : $1) . $');
    }
    print;
}

exit 0;
