#!/usr/bin/env python3
# Copyright © 2006 Progiciels Bourbeau-Pinard inc.
# François Pinard <pinard@iro.umontreal.ca>, 2006.

"""\
Recherche et diagnostic de poux stylistiques dans une hiérarchie Python.
"""

import sys

from Etc.pypoux import main

main(*sys.argv[1:])
