#!/usr/bin/env python3
# Copyright © 2000, 2003 Progiciels Bourbeau-Pinard inc.
# François Pinard <pinard@iro.umontreal.ca>, 2000.

"""\
Remove empty directories in the given directory hierarchies.

Usage: rmdir-empty [DIRECTORY]...

If not directory is given, the current directory is implied.
"""

import os
import sys


def main(*arguments):
    if arguments:
        for argument in arguments:
            os.path.walk(argument, walker, None)
    else:
        os.path.walk('.', walker, None)


def walker(dummy, directory, bases):
    while not bases:
        sys.stdout.write("Removing %s\n" % directory)
        os.rmdir(directory)
        directory, base = os.path.split(directory)
        if not directory or not os.path.isdir(directory):
            break
        bases = os.listdir(directory)

if __name__ == '__main__':
    main(*sys.argv[1:])
