#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# Copyright © 2000, 2002, 2003 Progiciels Bourbeau-Pinard inc.
# François Pinard <pinard@iro.umontreal.ca>, 2000.

u"""\
Éliminer les blancs suffixes, et les lignes vides en double.
"""

__metaclass__ = type
import sys

def main(*arguments):
    assert not arguments, arguments
    vide = True
    for ligne in sys.stdin:
        ligne = ligne.rstrip()
        if ligne:
            sys.stdout.write(ligne + '\n')
            vide = False
        elif not vide:
            sys.stdout.write('\n')
            vide = True

if __name__ == '__main__':
    main(*sys.argv[1:])
