#!/bin/sh
# u8 - Passer en mode UTF-8.
# Faire ". u8" dans le terminal voulu.

export LANG=fr_CA.UTF-8

if [ -n "$DISPLAY" ]; then
  echo '\033]5379;encoding=UTF-8;bg_color=ivory\007\c'
elif type 2>/dev/null unicode_start; then
  unicode_start
fi

