#!/usr/bin/env python3
# Copyright © 2002, 2003 Progiciels Bourbeau-Pinard inc.
# François Pinard <pinard@iro.umontreal.ca>, mai 2002.

"""\
Produit un fichier PostScript sur stdout présentant une fonte particulière
sur quatre pages, détaillant son apparence et sa métrique.

Usage: voir-fonte NOM

NOM est le nom d'une fonte PostScript.  Si NOM est "toutes", alors
toutes les fontes disponibles sont présentées.
"""

import os, subprocess, sys

def main(*arguments):
    assert len(arguments) == 1, arguments
    font = arguments[0]
    write = sys.stdout.write
    copier_prfont_ps(write)
    if font == 'toutes':
        write('FontDirectory {pop DoFont} forall\n')
    else:
        write('/%s DoFont\n' % font)

def copier_prfont_ps(write):
    for paquetage in 'gs_lib', 'ghostscript-library':
        for line in subprocess.Popen(
                'rpm -ql %s 2>/dev/null' % paquetage, shell=True,
                stdout=subprocess.PIPE).stdout:
            if line.endswith('/prfont.ps\n'):
                write(open(line.rstrip()).read())
                return
    sys.stderr.write("Pas trouvé `prfont.ps'.\n")
    sys.exit(1)

if __name__ == '__main__':
    main(*sys.argv[1:])
